### ISSUE TITLE
Undefined behavior in insertion code

### ISSUE THREAD

**Issue by BlackHoleFox** [droundy/tinyset#13] opened 2022-02-01 06:18 UTC
Hiya,

A contributor was looking to use this library in another project I help out with and I saw a good number of `unsafe` blocks so I figured I'd have a look. A quick look surfaced some trivially unsound code in `SetU32` (didnt look at the others in-depth, but they seem suspicious too).

In the insertion code, there is this block:
https://github.com/droundy/tinyset/blob/59159e7ce6d53aa77f0fb0fd08a07a1da6d57cb6/src/setu64.rs#L1027-L1034

At a glance you can see that it creates a mutable slice from `s.array`, and then it proceeds to keep both this reference and the original reference at `a` alive at the same time. This doesn't work because `a` is creating an independent mutable reference over parts of `s`, which are all mutable behind `s` too.

You can run `miri` to demonstrate the issue:
```
export MIRIFLAGS="-Zmiri-disable-isolation"
cargo +nightly miri test check_sets
```

Output:
```
cargo +nightly miri test check_sets
    Finished test [unoptimized + debuginfo] target(s) in 0.05s
     Running unittests (target/miri/x86_64-unknown-linux-gnu/debug/deps/tinyset-d6308c0e1804f018)

running 2 tests
test setu32::tests::check_sets ... error: Undefined Behavior: trying to reborrow for Unique at alloc570741+0xc, but parent tag <1529355> does not have an appropriate item in the borrow stack
    --> src/setu32.rs:1283:39
     |
1283 |                 InternalMut::Big { s, a }
     |                                       ^ trying to reborrow for Unique at alloc570741+0xc, but parent tag <1529355> does not have an appropriate item in the borrow stack
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information

     = note: inside `setu32::SetU32::internal_mut` at src/setu32.rs:1283:39
note: inside `setu32::SetU32::insert` at src/setu32.rs:907:15
    --> src/setu32.rs:907:15
     |
907  |         match self.internal_mut() {
     |               ^^^^^^^^^^^^^^^^^^^
note: inside `setu32::SetU32::insert` at src/setu32.rs:956:29
    --> src/setu32.rs:956:29
     |
956  | ...                   new.insert(x);
     |                       ^^^^^^^^^^^^^
note: inside `setu32::tests::check_set` at src/setu32.rs:1416:37
    --> src/setu32.rs:1416:37
     |
1416 |             let changed_something = s.insert(x);
     |                                     ^^^^^^^^^^^
note: inside `setu32::tests::check_sets` at src/setu32.rs:1466:9
    --> src/setu32.rs:1466:9
     |
1466 |         check_set(&[0, 1, 2, 3, 4, 5, 6, 7<<27, 8, 9, 10]);
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside closure at src/setu32.rs:1465:5
    --> src/setu32.rs:1465:5
     |
1464 |       #[test]
     |       ------- in this procedural macro expansion
1465 | /     fn check_sets() {
1466 | |         check_set(&[0, 1, 2, 3, 4, 5, 6, 7<<27, 8, 9, 10]);
1467 | |         check_set(&[]);
1468 | |         check_set(&[10]);
...    |
1483 | |         check_set(&[0, 1024, 1 << 30]);
1484 | |     }
     | |_____^
```

**Comment by droundy** [comment] 2022-02-03 22:32
First of all, thanks so much for reviewing my crate!

I think I'm understanding this.  The issue is that I create the `&mut` borrow of the array, and also maintain the `&mut` borrow of the `S`.  I thought that would be okay because I didn't then use the `array` portion of the `S`, but presumably that doesn't make it okay.  Would I be able to fix this then by creating another type that lacks the `array` field, and make `InternalMut::Big` take the new (smaller) version of `S`, so that the content of the two `&mut` borrows don't overlap, and we can guarantee the property that the `array` field is unused?

BTW I'm currently unable to install or use miri because
```
$ rustup +nightly component add miri
error: component 'miri' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel 'nightly'
Sometimes not all components are available in any given nightly. If you don't need the component, you can remove it with:

    rustup component remove --toolchain nightly --target x86_64-unknown-linux-gnu miri
```
and
```
$ export MIRIFLAGS="-Zmiri-disable-isolation"
$ cargo +nightly miri test check_sets
error: the 'miri' component which provides the command 'cargo-miri' is not available for the 'nightly-x86_64-unknown-linux-gnu' toolchain

```

**Comment by droundy** [comment] 2022-02-03 22:44
Okay, I've just implemented my suggestion (which turned out to be un-invasive for setu64.  The new code is at:

https://github.com/droundy/tinyset/blob/master/src/setu64.rs#L1028

Do you think this fixes the issue? (It seems to me like it should, since we have separate borrows of the two portions of the struct, but I can't see how to run miri to confirm this... plus I would prefer to also have a human eye look at the code.)  It looks like it was a pretty simple and non-invasive fix that I should be able to replicate to the other tiny sets easily enough.

**Comment by BlackHoleFox** [comment] 2022-02-05 00:34
With b9e3a64ab5c55ecad1f2be1ca11bfa3636e620d4, Miri no longer complains when I run `cargo +nightly miri test setu64` compared to ba66ec2c91359607e7afb9bdfc94496e2a7a3581 where it explodes, so from that side looks good :)

The code itself looks fine to me, its much easier (and possible) to prove its not doing anything strange since you can tell the field borrows are exclusive. 

> I thought that would be okay because I didn't then use the array portion of the S, but presumably that doesn't make it okay. 

While this makes sense just thinking about it, the language spec for Rust declares it UB to even *produce* an aliased mutable reference, even if you never use it. As soon as you do, its UB. See [the list here](https://doc.rust-lang.org/nomicon/what-unsafe-does.html).

**Comment by droundy** [comment] 2022-02-05 05:05
Great, thanks! I'll see about getting the others fixed in the same way when I get a chance.

**Closed as completed** 2022-02-09 17:20 UTC
